### 회원가입
POST http://localhost:8080/signup
Content-Type: application/json
Accept: */*

{
  "userId": "user03",
  "userPass": "pass03",
  "userName": "토끼",
  "userEmail": "rabbit@ohgiraffers.com",
  "role": "ALL"
}

### 로그인
POST http://localhost:8080/login
Content-Type: application/json
Accept: */*

{
  "id": "user03",
  "pass": "pass03"
}

### GET 요청
GET http://localhost:8080/test
Authorization: BEARER eyJkYXRlIjoxNzE3NTQ3MjUzNzU5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJSb2xlIjoiVVNFUiIsInN1YiI6Im9oZ2lyYWZmZXJzIHRva2VuIDogMiIsInVzZXJOYW1lIjoi7Yag64G8IiwiZXhwIjoxNzE3NjMzNjUzfQ.aBuk6xHMnMJ7Y0aUWvplx1xPwMhZ51Wk8R-hcgfdW74

### POST 요청
POST http://localhost:8080/test
Content-Type: application/json
Accept: */*
Authorization: BEARER eyJkYXRlIjoxNzE3NTQ3MjUzNzU5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJSb2xlIjoiVVNFUiIsInN1YiI6Im9oZ2lyYWZmZXJzIHRva2VuIDogMiIsInVzZXJOYW1lIjoi7Yag64G8IiwiZXhwIjoxNzE3NjMzNjUzfQ.aBuk6xHMnMJ7Y0aUWvplx1xPwMhZ51Wk8R-hcgfdW74