spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login
    username: sahmyook
    password: sahmyook

mybatis:
  mapper-locations: mapper/**/*.xml